# Generated by Django 2.2.2 on 2019-07-02 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0007_auto_20190702_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 3, 24, 48, 948203, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 3, 24, 48, 948237, tzinfo=utc)),
        ),
    ]
