"""
Django settings for Maesh Payment.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u8$em6-r#$i91=knt^uud&cy_r33imh4%cx9stx)newdmfd-17'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','10.202.1.158','192.168.1.70','maesh.io']

SITE = 'http://localhost:8000/'#'https://maesh.io:8000/'#'http://159.65.7.84:8000/'#'http://192.168.0.119:8000/'

API = {
    "dbs": {
        "url": "https://www.dbs.com/sandbox/api/sg/v1",
        "client_id": "6fce2916-d21e-4114-8433-8428d41effae",
        "client_secret": "527011b7-d982-478e-bd22-d28b54e33829"
    },
    "ocbc": {
        "url": "https://api.ocbc.com",
        "client_id": "1sQ5xa9nwB9i2E4l3BVAfyLMIe8a",
        "client_secret": "caHxtf_qg_pdCOBmsiMU5nR_fxAa",
        "access_token": "8c24fe6033a55fb4a8622239a0df7742"
    },
    "uob": {
        "url": "",
        "client_id": "",
        "client_secret": ""
    },
    "citi": {
        "url": "https://sandbox.apihub.citi.com/gcb/api",
        "client_id": "ff629055-00ed-4fcf-a4a3-8e99b2020a3c",
        "client_secret": "yK4rF0dK2xC5wN3fC7hF3vW6rQ8rY3kP5gE8rF6cT1gD6yP2iP"
    }
}

AUTHORIZATION = {
    "dbs": {
        'params': {
            'response_type': 'code',
            'client_id': API['dbs']['client_id'],
            'scope': 'Read',
            'redirect_uri': SITE+'payment_maesh_dbs',
            'state': '0399', #I think this number is random
        },
        'endpoint': API['dbs']['url']+'/oauth/authorize'
    },
    "ocbc": {
        'params': {
            'client_id': API['ocbc']['client_id'],
            'redirect_uri': SITE+'payment_maesh_ocbc',
            'scope': 'transactional'
        },
        'endpoint': API['ocbc']['url']+'/ocbcauthentication/api/oauth2/authorize'
    },
    "citi": {
        'params': {
            'response_type':'code',
            'client_id': API['citi']['client_id'],
            'scope': 'external_domestic_transfers',
            'countryCode':'SG',
            'businessCode':'GCB',
            'locale':'en_SG',
            'state':'12093', #This number has a purpose, but not now
            'redirect_uri': SITE+'payment_maesh_citi'
        },
        'endpoint': API['citi']['url']+'/authCode/oauth2/authorize'
    },
}

ACCESS_TOKEN = {
    "dbs": {
        'endpoint': API['dbs']['url']+'/oauth/tokens',
        'grant_type':'token',
    },
    "ocbc": {
        'endpoint': API['ocbc']['url']+'',
        'grant_type':'token',
    },
    "citi": {
        'endpoint': API['citi']['url']+'/authCode/oauth2/token/sg/gcb',
        'grant_type':'authorization_code',
    },
}

# Application definition

INSTALLED_APPS = [
    'payment.apps.PaymentConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'payment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'keuring/static/')