# Generated by Django 2.1.2 on 2019-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190517_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='party_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
