# Generated by Django 2.2.2 on 2019-07-02 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 3, 22, 19, 172180, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 3, 22, 19, 172241, tzinfo=utc)),
        ),
    ]
