# Generated by Django 2.2.2 on 2019-07-05 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20190705_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 5, 51, 53, 264415, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 5, 51, 53, 264449, tzinfo=utc)),
        ),
    ]
