# Generated by Django 2.2.2 on 2019-07-06 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20190705_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 7, 28, 50, 983266, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 7, 28, 50, 983410, tzinfo=utc)),
        ),
    ]
