# Generated by Django 2.2.2 on 2019-07-17 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20190706_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.AddField(
            model_name='credential',
            name='bank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='credential',
            name='scope',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='credential',
            name='cin_party_id',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 9, 21, 1, 668785, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 9, 21, 1, 668819, tzinfo=utc)),
        ),
    ]
