# Generated by Django 2.2.2 on 2019-07-18 02:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20190717_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Credential'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 2, 33, 43, 321696, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 2, 33, 43, 321732, tzinfo=utc)),
        ),
    ]
