# Generated by Django 2.2.2 on 2019-08-05 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20190718_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 4, 5, 33, 821094, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 4, 5, 33, 821130, tzinfo=utc)),
        ),
    ]
