# Generated by Django 2.2.2 on 2019-08-05 04:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20190805_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 4, 41, 48, 377009, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 4, 41, 48, 377041, tzinfo=utc)),
        ),
    ]
