# Generated by Django 2.2.2 on 2019-08-05 04:43

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20190805_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 4, 43, 43, 237672, tzinfo=utc)),
        ),
    ]
