# Generated by Django 2.2.2 on 2019-08-05 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20190805_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
