# Generated by Django 2.2.2 on 2019-08-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_transaction_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='companyName',
            new_name='company_name',
        ),
    ]
